# fly.toml app configuration file generated for telegram-bots-wild-dust-9487 on 2025-08-06T12:16:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'telegram-bots-wild-dust-9487'
primary_region = 'jnb'

[build]

[env]
  TOKEN = "dummy"
#[http_service]
#  internal_port = 8080
#  force_https = true
#  auto_stop_machines = 'stop'
#  auto_start_machines = true
#  min_machines_running = 0
#  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
